PersonnelTrackingSystem/PersonnelTrackingSystem.WebApp/Models/ShiftViewModel.cs
namespace PersonnelTrackingSystem.WebApp.Models
{
    public class ShiftViewModel
    {
        public ShiftViewModel()
        {
            Employees = new List<EmployeeViewModel>();
        }
        public int Id { get; set; }

        public DateTime WorkingDate { get; set; }
        public DateTime WorkingTime { get; set; }
        public int EmployeeId { get; set; }
        public string EmployeeName { get; set; }
        public List<EmployeeViewModel> Employees { get; set; }

    }
}

PersonnelTrackingSystem/PersonnelTrackingSystem.WebApp/Controllers/ShiftController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using PersonnelTrackingSystem.Business.Servicess;
using PersonnelTrackingSystem.Domain;
using PersonnelTrackingSystem.Materials;
using PersonnelTrackingSystem.Permissions;
using PersonnelTrackingSystem.Shifts;
using PersonnelTrackingSystem.WebApp.Models;
using System.Collections.Generic;
using System.Data;

namespace PersonnelTrackingSystem.WebApp.Controllers
{
    [Authorize]
    public class ShiftController : Controller
    {
        private readonly ShiftService _shiftService = new ShiftService();
        private readonly EmployeeService _employeeService = new EmployeeService();

        [Authorize]
        public ActionResult EmployeeShifts()
        {
            List<ShiftDto> shifts = _shiftService.GetAllByUser(User).ToList();
            return View(shifts);
        }

        public ActionResult MyShifts()
        {
            List<ShiftDto> shifts = _shiftService.GetAll().ToList();
            return View(shifts);

        }
        public ActionResult Index()
        {
            List<ShiftViewModel> shifts = _shiftService.GetAllByUser(User).Select(s => new ShiftViewModel
            {
                EmployeeId= s.EmployeeId,
                EmployeeName = _employeeService.GetFullNameById(s.EmployeeId),
                Id= s.Id,
                WorkingDate= s.WorkingDate,
                WorkingTime= s.WorkingTime
            }).ToList();
            return View(shifts);
        }
        public ActionResult Details(int id)
        {
            return View();
        }

        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            ShiftViewModel model=new ShiftViewModel();
            model.Employees = _employeeService.GetAllByUser(User).Select(x => new EmployeeViewModel
            {
                FullName = x.FirstName + ' ' + x.LastName,
                Id = x.Id
            }).ToList();
            model.WorkingDate = DateTime.Now;
            model.WorkingTime = DateTime.Now.Date;

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ShiftViewModel shift)
        {
            ShiftDto shiftDto = new ShiftDto()
            {
                WorkingTime= shift.WorkingTime,
                EmployeeId= shift.EmployeeId,   
                WorkingDate= shift.WorkingDate,
                Id=shift.Id
            };

            var result = _shiftService.Create(shiftDto);
            if (result.IsSuccess)
            {
                TempData["ResultMessage"] = result.Message;
                return RedirectToAction("Index");
            }
            else
            {
                TempData["ResultMessage"] = result.Message;

                shift.Employees = _employeeService.GetAllByUser(User).Select(x => new EmployeeViewModel
                {
                    FullName = x.FirstName + ' ' + x.LastName,
                    Id = x.Id
                }).ToList();
                return View(shift);
            }
        }

        [Authorize(Roles = "Admin")]
        public ActionResult Update(int id)
        {
            ShiftViewModel model = new ShiftViewModel();
            model.Employees = _employeeService.GetAllByUser(User).Select(x => new EmployeeViewModel
            {
                FullName = x.FirstName + ' ' + x.LastName,
                Id = x.Id
            }).ToList();
            ShiftDto shiftDto=_shiftService.GetById(id);
            model.WorkingTime = shiftDto.WorkingTime;
            model.EmployeeId = shiftDto.EmployeeId;
            model.WorkingDate = shiftDto.WorkingDate;
            model.Id = shiftDto.Id; 
            return View(model);  
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Update(ShiftDto shift)
        {
            var commandResult = _shiftService.Update(shift);

            if (commandResult.IsSuccess)
            {
                TempData["ResultMessage"] = commandResult.Message;
                return RedirectToAction("Index");
            }
            else
            {
                TempData["ResultMessage"] = commandResult.Message;

                ShiftViewModel model = new ShiftViewModel();
                model.Employees = _employeeService.GetAllByUser(User).Select(x => new EmployeeViewModel
                {
                    FullName = x.FirstName + ' ' + x.LastName,
                    Id = x.Id
                }).ToList();
                model.WorkingTime = shift.WorkingTime;
                model.EmployeeId = shift.EmployeeId;
                model.WorkingDate = shift.WorkingDate;
                model.Id = shift.Id;

                return View(model);
            }
        }


        [HttpPost]
        public ActionResult Delete(ShiftDto shift)
        {
            var commandResult = _shiftService.Delete(shift);
            if (commandResult.IsSuccess)
            {
                TempData["ResultMessage"] = commandResult.Message;
            }
            else
            {
                ViewBag.ResultMessage = commandResult.Message;
            }
            return RedirectToAction("Index");
        }
    }
}

PersonnelTrackingSystem/PersonnelTrackingSystem.WebApp/Views/Shift/Create.cshtml
@model PersonnelTrackingSystem.WebApp.Models.ShiftViewModel

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h4>Yeni Mesai Ekleme</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
             <div class="form-group">
                <div class="card card-body border-0 shadow mb-4">
                    <div class="row">
                        <div class="form-group">
                            <label asp-for="Employees" class="control-label">Personel Bilgisi</label>
                            <select asp-for="EmployeeId" class="form-select" required
                                    asp-items="@(new SelectList(Model.Employees, "Id", "FullName"))">
                                <option value="">Seçiniz</option>
                            </select>
                        </div>
                        
                        <div class="row">
                            <div class="col-md-6 mb-3">
                                <label asp-for="WorkingDate" class="control-label">Mesai Tarihi</label>
                                <input asp-for="WorkingDate" class="form-control" required />
                                <span asp-validation-for="WorkingDate" class="text-danger"></span>
                            </div>
                            <div class="col-md-6 mb-3">
                                <label asp-for="WorkingTime" class="control-label">Mesai Süresi</label>
                                <input asp-for="WorkingTime" class="form-control" type="time" min="00:00" max="23:59" required />
                                <span asp-validation-for="WorkingTime" class="text-danger"></span>
                            </div>
                        </div>

                    </div>
                    <div class="mt-3">
                        <button class="btn btn-gray-800 mt-2 animate-up-2" type="submit">Kaydet</button>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>


<hr />

<div class="row">
    <div class="form-group">
        <a class="btn btn-light btn-primary" asp-action="Index">Listeye Geri Dön</a>
    </div>
</div>

PersonnelTrackingSystem/PersonnelTrackingSystem.WebApp/Views/Shift/Index.cshtml
@model IEnumerable<ShiftViewModel>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="py-4">
    <nav aria-label="breadcrumb" class="d-none d-md-inline-block">
        <ol class="breadcrumb breadcrumb-dark breadcrumb-transparent">
            <li class="breadcrumb-item" style="font-family:tahoma;font-weight:bold;font-size:125%">
                <a href="#">
                    <svg class="icon icon-xxs" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 12l2-2m0 0l7-7 7 7M5 10v10a1 1 0 001 1h3m10-11l2 2m-2-2v10a1 1 0 01-1 1h-3m-6 0a1 1 0 001-1v-4a1 1 0 011-1h2a1 1 0 011 1v4a1 1 0 001 1m-6 0h6"></path></svg>
                </a>
            </li>
            <li class="breadcrumb-item active" style="font-family:tahoma;font-weight:bold;font-size:125%" aria-current="page">Mesai Listesi</li>
        </ol>
    </nav>
</div>

<div class="row">
    <div class="col-12">
        <div class="float-end">
            @if (User.IsInRole("Admin"))
            {
                <a class="btn btn-outline-primary btn-sm" asp-controller="Shift" asp-action="Create">Personel Mesai Girişi</a>
            }
        </div>
        <div class="float-start col-4">
            @if (TempData.ContainsKey("ResultMessage"))
            {
                <div class="alert alert-success">
                    @TempData["ResultMessage"]
                </div>
            }
        </div>
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Personel Adı</th>
                    <th>Mesai Tarihi</th>
                    <th>Mesai Süresi</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var shift in Model)
                {
                    <tr>
                        <td>@shift.EmployeeName</td>
                        <td>@shift.WorkingDate</td>
                        <td>@shift.WorkingTime.ToString("HH:mm")</td>


                        <td class="text-end">
                            @if (User.IsInRole("Admin"))
                            {
                                <a class="btn btn-outline-primary btn-sm" asp-controller="Shift" asp-action="Update" asp-route-id="@shift.Id">Düzenle </a>
                                <form asp-action="Delete" method="post" class="delete-form d-inline-block" onclick="return confirm('Bu mesaiyi silmek istediğinize emin misiniz?');">
                                    <input type="hidden" value="@shift.Id" name="id">
                                    <button class="btn btn-outline-danger btn-sm">Sil</button>
                                </form>
                            }
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

PersonnelTrackingSystem/PersonnelTrackingSystem.WebApp/Views/Shift/Index_.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="py-4">
    <nav aria-label="breadcrumb" class="d-none d-md-inline-block">
        <ol class="breadcrumb breadcrumb-dark breadcrumb-transparent">
            <li class="breadcrumb-item" style="font-family:tahoma;font-weight:bold;font-size:125%">
                <a href="#">
                    <svg class="icon icon-xxs" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 12l2-2m0 0l7-7 7 7M5 10v10a1 1 0 001 1h3m10-11l2 2m-2-2v10a1 1 0 01-1 1h-3m-6 0a1 1 0 001-1v-4a1 1 0 011-1h2a1 1 0 011 1v4a1 1 0 001 1m-6 0h6"></path></svg>
                </a>
            </li>
            <li class="breadcrumb-item active" style="font-family:tahoma;font-weight:bold;font-size:125%" aria-current="page">Mesai Listesi</li>
        </ol>
    </nav>
</div>
<div class="row">
    <div class="col-12 mb-4">
        <div class="card border-light shadow-sm components-section">
            <div class="card-body">
                @if (User.IsInRole("Admin"))
                {
                    <button class="btn btn-lg btn-primary" type="button">Personel'e Yeni Mesai Gir</button>
                    <a asp-action="EmployeeShifts" asp-controller="Shift" class="btn btn-lg btn-primary" type="button">Personel Mesaileri</a>
                }
            </div>
        </div>
    </div>
</div>

PersonnelTrackingSystem/PersonnelTrackingSystem.WebApp/Views/Shift/Update.cshtml
@model PersonnelTrackingSystem.WebApp.Models.ShiftViewModel

@{
    ViewData["Title"] = "Update";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h4>Yeni Mesai Ekleme</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Update">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <div class="card card-body border-0 shadow mb-4">
                    <div class="row">
                        <div class="form-group">
                            <label asp-for="Employees" class="control-label">Personel Bilgisi</label>
                            <select asp-for="EmployeeId" class="form-select" required
                                    asp-items="@(new SelectList(Model.Employees, "Id", "FullName"))">
                                <option value="">Seçiniz</option>
                            </select>
                        </div>

                        <div class="row">
                            <div class="col-md-6 mb-3">
                                <label asp-for="WorkingDate" class="control-label">Mesai Tarihi</label>
                                <input asp-for="WorkingDate" class="form-control" required />
                                <span asp-validation-for="WorkingDate" class="text-danger"></span>
                            </div>
                            <div class="col-md-6 mb-3">
                                <label asp-for="WorkingTime" class="control-label">Mesai Süresi</label>
                                <input asp-for="WorkingTime" class="form-control" type="time" min="00:00" max="23:59" required />
                                <span asp-validation-for="WorkingTime" class="text-danger"></span>
                            </div>
                        </div>

                    </div>
                    <div class="mt-3">
                        <button class="btn btn-gray-800 mt-2 animate-up-2" type="submit">Kaydet</button>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>


<hr />

<div class="row">
    <div class="form-group">
        <a class="btn btn-light btn-primary" asp-action="Index">Listeye Geri Dön</a>
    </div>
</div>