PersonnelTrackingSystem/PersonnelTrackingSystem.WebApp/Models/MaterialViewModel.cs
namespace PersonnelTrackingSystem.WebApp.Models
{
    public class MaterialViewModel
    {
        public MaterialViewModel()
        {
            Employees = new List<EmployeeViewModel>();
        }
        public int Id { get; set; }

        public string Request { get; set; }
        public object EmployeeName { get; internal set; }
        public int EmployeeId { get; set; }
        public List<EmployeeViewModel> Employees { get; set; }


    }
}

PersonnelTrackingSystem/PersonnelTrackingSystem.WebApp/Controllers/MaterialController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using PersonnelTrackingSystem.Business.Servicess;
using PersonnelTrackingSystem.Materials;
using PersonnelTrackingSystem.WebApp.Models;

namespace PersonnelTrackingSystem.WebApp.Controllers
{
    [Authorize]
    public class MaterialController : Controller
    {
        private readonly MaterialService _materialService = new MaterialService();
        private readonly EmployeeService _employeeService = new EmployeeService();

        public ActionResult Index()
        {
            var materials = _materialService.GetAllByUser(User).Select(s => new MaterialViewModel
            {
                EmployeeId= s.EmployeeId,
                EmployeeName = _employeeService.GetFullNameById(s.EmployeeId),
                Id= s.Id,
                Request = s.Request,

            });
            return View(materials);
        }

        public ActionResult Create()
        {
            MaterialViewModel materialViewModel = new MaterialViewModel();
            materialViewModel.Employees = _employeeService.GetAllByUser(User).Select(x => new EmployeeViewModel
            {
                FullName = x.FirstName + ' ' + x.LastName,
                Id = x.Id
            }).ToList();
           

            return View(materialViewModel);
        }

        [HttpPost]
        public ActionResult Create(MaterialViewModel material)
        {
            MaterialDto materialDto = new MaterialDto()
            {
               EmployeeId= material.EmployeeId,
               Id= material.Id,
               Request= material.Request, 
               
            };

            var result = _materialService.Create(materialDto);
            if (result.IsSuccess)
            {
                TempData["ResultMessage"] = result.Message;
                return RedirectToAction("Index");
            }
            else
            {
                material.Employees = _employeeService.GetAllByUser(User).Select(x => new EmployeeViewModel
                {
                    FullName = x.FirstName + ' ' + x.LastName,
                    Id = x.Id
                }).ToList();
                TempData["ResultMessage"] = result.Message;
                return View();
            }
        }

        public ActionResult Update(int id)
        {
            MaterialViewModel model = new MaterialViewModel();
            model.Employees = _employeeService.GetAllByUser(User).Select(x => new EmployeeViewModel
            {
                FullName = x.FirstName + ' ' + x.LastName,
                Id = x.Id
            }).ToList();


            MaterialDto materialDto = _materialService.GetById(id);
            model.EmployeeId = materialDto.EmployeeId;
            model.Request = materialDto.Request;

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Update(MaterialDto material)
        {
            var commandResult = _materialService.Update(material);

            if (commandResult.IsSuccess)
            {
                TempData["ResultMessage"] = commandResult.Message;
                return RedirectToAction("Index");
            }
            else
            {

                TempData["ResultMessage"] = commandResult.Message;
                return View(material);
            }
        }

        public ActionResult Delete(MaterialDto material)
        {
            var commandResult = _materialService.Delete(material);
            if (commandResult.IsSuccess)
            {
                TempData["ResultMessage"] = commandResult.Message;
            }
            else
            {
                ViewBag.ResultMessage = commandResult.Message;
            }
            return RedirectToAction("Index");
        }

    }
}

PersonnelTrackingSystem/PersonnelTrackingSystem.WebApp/Views/Material/Create.cshtml
@model MaterialViewModel

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h4>Yeni Malzeme Ekleme</h4>

<div class="row">
    <div class="col-12 col-xl-8">
        @if (TempData.ContainsKey("ResultMessage"))
        {
            <div class="alert alert-danger ">
                @TempData["ResultMessage"]
            </div>
        }
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <div class="card card-body border-0 shadow mb-4">
                    <h2 class="h5 mb-4">Malzeme Bilgileri</h2>
                    <div class="row">
                        <div class="col-md-6 mb-3">
                            <label asp-for="Employees" class="control-label">Personel Bilgisi</label>
                            <select asp-for="EmployeeId" class="form-select" required
                                    asp-items="@(new SelectList(Model.Employees, "Id", "FullName"))">
                                <option value="">Lütfen Seçiniz</option>
                            </select>
                        </div>
                        <div class="col-md-6 mb-3">
                            <label asp-for="Request" class="control-label">İstek</label>
                            <input asp-for="Request" class="form-control" required />
                            <span asp-validation-for="Request" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="mt-3">
                        <button class="btn btn-gray-800 mt-2 animate-up-2" type="submit">Kaydet</button>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Listeye Geri Dön</a>
</div>

PersonnelTrackingSystem/PersonnelTrackingSystem.WebApp/Views/Material/Index.cshtml
@model IEnumerable<MaterialViewModel>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="py-4">
    <nav aria-label="breadcrumb" class="d-none d-md-inline-block">
        <ol class="breadcrumb breadcrumb-dark breadcrumb-transparent">
            <li class="breadcrumb-item" style="font-family:tahoma;font-weight:bold;font-size:125%">
                <a href="#">
                    <svg class="icon icon-xxs" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 12l2-2m0 0l7-7 7 7M5 10v10a1 1 0 001 1h3m10-11l2 2m-2-2v10a1 1 0 01-1 1h-3m-6 0a1 1 0 001-1v-4a1 1 0 011-1h2a1 1 0 011 1v4a1 1 0 001 1m-6 0h6"></path></svg>
                </a>
            </li>
            <li class="breadcrumb-item active" style="font-family:tahoma;font-weight:bold;font-size:125%" aria-current="page">Malzeme Listesi</li>
        </ol>
    </nav>
</div>

<div class="row">
    <div class="col-12">
        <div class="float-end">
            <a class="btn btn-outline-primary btn-sm" asp-controller="Material" asp-action="Create">Yeni Malzeme Ekle</a>
        </div>
        <div class="float-start col-4">
            @if (TempData.ContainsKey("ResultMessage"))
            {
                <div class="alert alert-success">
                    @TempData["ResultMessage"]
                </div>
            }
        </div>
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Personel Adı</th>
                    <th>İstek</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var material in Model)
                {
                    <tr>
                        <td>@material.EmployeeName</td>
                        <td>@material.Request</td>


                        <td class="text-end">
                            <a class="btn btn-outline-primary btn-sm" asp-controller="Material" asp-action="Update" asp-route-id="@material.Id">Düzenle </a>
                            <form asp-action="Delete" method="post" class="delete-form d-inline-block" onclick="return confirm('Bu malzemeyi silmek istediğinize emin misiniz?');">
                                <input type="hidden" value="@material.Id" name="id">
                                <button class="btn btn-outline-danger btn-sm">Sil</button>
                            </form>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

PersonnelTrackingSystem/PersonnelTrackingSystem.WebApp/Views/Material/Update.cshtml
@model PersonnelTrackingSystem.WebApp.Models.MaterialViewModel

@{
    ViewData["Title"] = "Update";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<h4>Malzeme Bilgilerini Güncelleme</h4>

<div class="row">
    <div class="col-12 col-xl-8">
        @if (TempData.ContainsKey("ResultMessage"))
        {
            <div class="alert alert-danger ">
                @TempData["ResultMessage"]
            </div>
        }
        <form asp-action="Update">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <div class="card card-body border-0 shadow mb-4">
                    <h2 class="h5 mb-4">Malzeme Bilgileri</h2>
                    <div class="row">
                        <div class="col-md-6 mb-3">
                            <label asp-for="Employees" class="control-label">Personel Bilgisi</label>
                            <select asp-for="EmployeeId" class="form-select" required
                                    asp-items="@(new SelectList(Model.Employees, "Id", "FullName"))">
                                <option value="">Lütfen Seçiniz</option>
                            </select>
                        </div>
                        <div class="col-md-6 mb-3">
                            <label asp-for="Request" class="control-label">İstek</label>
                            <input asp-for="Request" class="form-control" required />
                            <span asp-validation-for="Request" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="mt-3">
                        <button class="btn btn-gray-800 mt-2 animate-up-2" type="submit">Kaydet</button>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Listeye Geri Dön</a>
</div>